Repository Eoxia/EasyURL, pull requests merged in 2024-09, with the labels that each got.

#73 #70 [Class/Js] add: export of url in csv and reword link creation in js
  class/exportshortenerdocument.class.php
  class/shortener.class.php
  js/easyurl.min.js
  js/modules/exportshortener.js
  js/modules/shortener.js
  langs/fr_FR/easyurl.lang
  sql/llx_easyurl_shortener.sql
  view/easyurltools.php
  view/shortener/shortener_card.php
Labels: 5

#75 #70 [Tools] fix: missing ref for exportshortener
  core/modules/easyurl/easyurldocuments/exportshortenerdocument/index.php
  core/modules/easyurl/easyurldocuments/exportshortenerdocument/mod_exportshortenerdocument_standard.php
  core/modules/easyurl/easyurldocuments/index.php
  core/modules/modEasyURL.class.php
  view/easyurltools.php
Labels: 1, Bug

#76 #70 [Trad] fix: trad and dayhourlog for export
  class/exportshortenerdocument.class.php
  langs/fr_FR/easyurl.lang
Labels: 0, Enhancement, Translation
