Repository Eoxia/EasyURL, pull requests merged in 2025-02, with the labels that each got.

#94 #1975 [PublicInterfaceJs] fix: url in select2 ref
  js/easyurl.min.js
  js/modules/publicinterface.js
Labels: 2, Bug

#87 #71 [Shortener] add: showInputField for prevent dolibarr 20 bug
  class/shortener.class.php
  view/shortener/shortener_card.php
Labels: 1, Bug, Enhancement

#90 #84 [ShortenerCard] add: button to unassign shortener
  class/shortener.class.php
  langs/fr_FR/easyurl.lang
  view/shortener/shortener_card.php
Labels: 3, Enhancement

#97 #86 [Shortener] fix: showInputField improve for manage case saturne_get_objects_metadata
  class/shortener.class.php
  js/easyurl.min.js
  js/modules/shortener.js
  view/shortener/shortener_card.php
Labels: 2, Bug

#98 #61 [Lib] add: init_easy_url_curl fucntion for optimize curl functionnality
  admin/setup.php
  class/actions_easyurl.class.php
  class/shortener.class.php
  langs/fr_FR/easyurl.lang
  lib/easyurl_function.lib.php
Labels: 2, Enhancement

#102 #100 [ExportShortenerJS] fix: button stay gray when error
  js/easyurl.min.js
  js/modules/exportshortener.js
Labels: 0, Bug

#101 #99 [ShortenerJS] fix: Create export when pressing enter on field
  js/easyurl.min.js
  js/modules/shortener.js
  view/easyurltools.php
Labels: 1, Bug

#106 #105 [PublicShortener] add: management of public interface with external module
  class/actions_easyurl.class.php
  public/frontend/assign_qrcode_view.tpl.php
  public/shortener/public_shortener.php
Labels: 3, Enhancement

#109 #107 [AssignQRCocePublic] add: qrcode list
  class/actions_easyurl.class.php
  class/shortener.class.php
  public/frontend/assign_qrcode_view.tpl.php
  public/shortener/public_shortener.php
Labels: 2, Bug, Enhancement
